### ISSUE TITLE
Data normalization

### ISSUE THREAD

**Issue by Dankrunchy** [Benno49/data-literacy-project#5]
### TODO 

- [x] regard inflation 
- [x] different currencies
- [ ] director/actor periods
- [x] release year
- [x] release month/date area
- [ ] Critics score weighted with credibility (budget x review count)
